package main

func main() {
	// fmt.Println("Hello World! This is Daniel first Go program\n More Codes to come")
	// testDataTypeExample()
	// testconstantExamples()
	// testForLoopsExamples()
	// testWhileLoopsExamples()
	// testForloopOnArray()
	// testForloopOnArrayMutation()
	// testForEachLoopUsingRangeOnArray()
	// testIfStatements()
	// testSwitchCaseStatemets()
	// testArraysExample()
	// testSliceExample()
	testUpdateSliceExample()
	// testMapExample()
	// testString()
	// testFuctionWithFunctionArgument(1, 3)
	// testVariadicFunction()
	// testStructs()
	// testInterface()
	// testTypePlayGround()
	// testDerivedTypesOfmapOfEvents()
}
